customer_service(Django)/urls.py
from django.urls import path
from . import views

app_name = 'customer_service'

urlpatterns = [
    path('customer_page/', views.inquire_list, name='iq_list'),
    path('customer_write/', views.write, name='iq_write'),
    path('customer_edit/', views.edit, name='iq_edit'),
    path('cutomer_editok/', views.edit_ok, name='edit_ok'),
    path('cutomer_delete/<int:pid>', views.delete, name='delete'),    
    path('notice_page/', views.notice_list, name='nt_list'),
    path('notice_details/<str:pk>', views.notice_details, name='nt_details'),
    path('notice_write/', views.write_nt, name='nt_write'),
    path('', views.view_ordno, name='ordno'),
       
]

customer_service(Django)/models.py
from django.db import models
from django.conf import settings
from accounts.models import Profile

# Create your models here.


class CustomerService(models.Model):
    category = models.CharField(verbose_name='카테고리', max_length=10, default="")
    order_num = models.CharField(verbose_name='주문번호', max_length=20)
    post_title = models.CharField(verbose_name='제목', max_length=20, default="")
    post_content = models.TextField(verbose_name='내용', max_length=250, default="")
    person_name = models.CharField(verbose_name='작성자', max_length=20)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    create_date = models.DateTimeField(verbose_name='작성일', auto_now_add=True)

    answer=models.CharField(verbose_name='답변', max_length=100, default="")

    def __str__(self):
        return self.post_title # 데이터 조회 시 제목을 보여줌.

    class Meta:
        db_table = "CustomerService"

    objects = models.Manager()  # 자동완성 .objects 를 사용하기 위한 설정

class Notice(models.Model):
    category = models.CharField(verbose_name='분류', max_length=10, default="")
    hit = models.PositiveIntegerField(verbose_name='조회수', default=0)
    title = models.CharField(verbose_name='제목', max_length=20, default="")
    content = models.TextField(verbose_name='내용', max_length=250, default="")
    person_name = models.CharField(verbose_name='작성자', max_length=20)
    create_date = models.DateTimeField(verbose_name='작성일', auto_now_add=True)

    def __str__(self):
        return self.title # 데이터 조회 시 제목을 보여줌.

    class Meta:
        db_table = "Notice"
    
    @property
    def update_counter(self):
        self.hit = self.hit+1
        self.save()

customer_service(Django)/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import CustomerService, Notice
from accounts.models import Profile
from django.contrib.auth.models import User as auth_User
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.urls import reverse

# 로그인 시 작성자 이름을 어케 가져올까.
# Create your views here.





def inquire_list(request): # 문의 목록 표시
    user = request.user
    iq_list = CustomerService.objects.order_by('-create_date')
    value=0
    datas = {
        'iq_list':iq_list,
        'value':value,
    }
    # 로그인 세션이 존재할 경우 post로 받아온 값이 있을 경우
    # 번호(key) 카테고리 제목 작성자(forienkey) 작성일을 
    # customer_page.html에 표시
    if user.is_authenticated:
        return render(request, "customer_service/customer_page.html", datas)
        
    if not user.is_authenticated:
        return render(request, "accounts/login.html")
        # login이 안되어있을 경우 -> 로그인 페이지로 이동
    
    



def write(request):
    user = request.user
    try:
        profile = Profile.objects.get(user=user)
        email = profile.email
        phone = profile.phone_number
    except:
        data={
            'admin':1,
        }
        return render(request, "customer_service/customer_page.html",data)
    

    if request.method=='POST':
        category = request.POST.get('itemcd', None)
        order_num = request.POST.get('ordno', None)
        post_title = request.POST.get('subject', None)
        post_content = request.POST.get('contents', None)
        person_name = profile.person_name
        try:
            image = request.FILES['file[]']
        except: image = "no_image"
        create_date = DateFormat(datetime.now()).format('Y-m-d')
        
        print(category,order_num,post_title,post_content,person_name,image,create_date)
        
        cs = CustomerService(
            category=category,
            order_num=order_num,
            post_title=post_title,
            post_content=post_content,
            person_name=person_name,
            create_date=create_date,
            image=image)
        
        try:
            cs.save()
        except Exception as e:
            print(e)        
        
        # return render(request, 'customer_service/customer_page.html', datas)
        return redirect('/customer_service/customer_page')
    # (post)
    # 글쓰기 페이지로 부터 post로 받아온 값이 있을 경우
    # db로 전달 후
    # inquire_list로 연결 (alert창:문의가 접수되었습니다.)
    

    data = {
        'email':email,
        'phone':phone,
    }

    return render(request, "customer_service/customer_write.html",data)
    

def edit(request):
    
    if request.method=="POST":
        title = request.POST.get('title',None)
        uid = request.POST.get('user',None)
        print(title,uid)
        user = auth_User.objects.get(username=uid)

        try:
            profile = Profile.objects.get(user=user)
        except:
            print("no user info")
        email = profile.email
        phone = profile.phone_number
        data = {
            'title':title,
            'email':email,
            'phone':phone,
        }

    return render(request, "customer_service/customer_edit.html",data)

def edit_ok(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method=="POST":
        category = request.POST.get('itemcd', None)
        order_num = request.POST.get('ordno', None)
        post_title = request.POST.get('subject', None)
        post_content = request.POST.get('contents', None)
        person_name = profile.person_name
        try:
            image = request.FILES['file[]']
        except: image = "no_image"
        create_date = DateFormat(datetime.now()).format('Y-m-d')
        
        print(category,order_num,post_title,post_content,person_name,image,create_date)
        
        # update query
        cs = CustomerService.objects.get(post_title=post_title)
        cs.category = category
        cs.order_num=order_num
        cs.post_content=post_content
        cs.image=image
        cs.create_date=create_date
        try:
            cs.save()
        except Exception as e:
            print(e)        
        return redirect('/customer_service/customer_page')



def delete(request, pid):
    cs = CustomerService.objects.get(id=pid)
    cs.delete()    
    return redirect('/customer_service/customer_page')
    

def view_ordno(request):
    return render(request, "customer_service/order_content.html")




# def answer(request):
#     # 관리자가 문의답변을 했을 경우 db를 반영함.
#     # 그렇지 않을 경우 1문의답변이없는경우 템플릿을 보임.
     

def notice_list(request): # 문의 목록 표시
    nt_list = Notice.objects.order_by('-create_date')
    datas = {
        'list':nt_list,
    }
    return render(request,"customer_service/notice_page.html", datas)
    # login이 안되어있을 경우 -> 로그인 페이지로 이동
    # 공지사항 리스트
        
def notice_details(request, pk):
    nt = Notice.objects.get(title=pk)
    print(nt.title)
    
    data = {
        'hit':nt.hit,
        'title':nt.title,
        'content':nt.content,
        'person_name':nt.person_name,
        'date':nt.create_date,
    }
    return render(request,"customer_service/notice_details.html", data)
#     # notice_list에서 제목을 클릭했을 때 해당 내용(content)볼 수 있음.

def write_nt(request):

    if request.method=='POST':
        category = request.POST.get('itemcd', None)
        hit = 0
        title = request.POST.get('subject', None)
        content = request.POST.get('contents', None)
        person_name = '관리자'
        create_date = DateFormat(datetime.now()).format('Y-m-d')
        
        print(category,hit,title,content,person_name,create_date)
        
        nt = Notice(
            category=category,
            hit=hit,
            title=title,
            content=content,
            person_name=person_name,
            create_date=create_date,
            )
        
        try:
            nt.save()
        except Exception as e:
            print(e)        
        
        return redirect('/customer_service/notice_page')
    return render(request, "customer_service/notice_write.html")

customer_service(Django)/templates/customer_service/customer_page.html
{% extends 'base.html' %} {% block content %} {% load static%}

<head>
    <meta charset="utf-8">
    <script src="http://code.jquery.com/jquery.min.js"></script>
    <title>customer service page</title>
    <link rel="stylesheet" href="{% static 'customer_service/css/customer.css' %}">
    <link rel="stylesheet" href="{% static 'customer_service/css/section2.css' %}">
    <link rel="stylesheet" href="{% static 'customer_service/css/normalize.css' %}">
    <script src="{% static 'customer_service/js/customer.js' %}"></script>

</head>
{% if admin == 1%}

<script>
    alert("관리자 권한으로 접근할 수 없습니다."); // 고객센터 페이지는 고객만이 문의작성이 가능하기 때문에 관리자접근을 제한한다.
    history.back(-1);
</script>
{% endif %}
<div class="page_aticle aticle_type2">

    <div id="snb" class="snb_cc">
        <h2 class="tit_snb">고객센터</h2>
        <div class="inner_snb">
            <ul class="list_menu">
                <li>
                    <a href="{% url 'customer_service:nt_list' %}">공지사항</a>
                </li>
                <li class="on">
                    <a href="{% url 'customer_service:iq_list' %}">1:1 문의</a>
                </li>

            </ul>
        </div>
        <a href="{% url 'customer_service:iq_list' %}" class="link_inquire"><span class="emph">도움이 필요하신가요 ?</span> 1:1 문의하기</a>
    </div>
    <div class="page_section section_qna">
        <div class="head_aticle">
            <h2 class="tit">1:1 문의</h2>
        </div>

        <div id="content_write">
            <table class="xans-board-listheader" width="100%">
                <tbody>
                    <tr class="input_txt">
                        <th width="8%">번호</th>
                        <th width="15%">카테고리 </th>
                        <th>제목</th>
                        <th width="12%">작성자</th>
                        <th width="12%">작성일</th>
                    </tr>
                </tbody>
            </table>
            <!-- 1-1. 문의내역이 없을 경우 문구.-->
            {% if iq_list|length == 0 %}
            <div class="no_data" style="padding:150px 0 148px;border-top:1px solid #e6e6e6;border-bottom:1px solid #e6e6e6;font-size:12px;color:#4c4c4c">
                1:1 문의 내역이 존재하지 않습니다.
            </div>
            {% endif %}

        </div>


        <!-- 2-1. 만약 문의내용이 있을 경우 리스트(배열)-->
        {% for iq in iq_list %}
        <div class="mypage_wrap" style="float:none;width:100%">
            <form action="{% url 'customer_service:iq_edit' %}" id="fm_send_tit" method="post">
                {% csrf_token %}

                <input type="hidden" name="title" id="title" value="{{iq.post_title}}">
                <input type="hidden" name="user" id="user" value="{{user.username}}">
                <table class="table_faq" width="100%" onclick="">
                    <tbody>
                        <tr>
                            <td width="8%" align="center">{{forloop.counter}}</td>
                            <td width="15%" align="center" class="stxt"><b>[ {{iq.category}}문의 ]</b></td>
                            <td style="padding-top:5px; padding-bottom:5px;">
                                <span id="tit" name="tit" value="">{{iq.post_title}}</span> {% if iq.answer|length == 0 %}
                                <span style="color:#007FC8;" class="stxt">[0]</span> {% else %}
                                <span style="color:#007FC8;" class="stxt">[1]</span> {% endif %}
                            </td>
                            <td width="12%" align="center">{{iq.person_name}}</td>
                            <td width="12%" align="center">{{iq.create_date|date:'Y-m-d'}}</td>
                        </tr>
                    </tbody>
                </table>
                <!-- 클릭했을 때 열리는 부분. (행)-->
                <div class="table_faq plus" style="display:none;padding:30px; border-top:1px solid #e6e6e6">
                    <div width="100%" style="padding-left:55px; padding-bottom:20px;">[ {{iq.category}}문의 ] {{iq.title}}</div>
                    <div width="100%" style="padding-left:55px;">{{iq.post_content}}</div>
                    <div class="goods-review-grp-btn" style="text-align:right;margin:10px;">
                        {% if iq.answer|length == 0%}
                        <button type="button" class="styled-button" id="edit">수정</button> {% endif %}
                        <a href="{% url 'customer_service:delete' iq.id %} ">
                            <button type="button" class="styled-button" id="delete">삭제</button>
                        </a>

                    </div>

                    <div class="table_faq_anwser" style="display: block; padding: 30px; border-top: 1px solid rgb(230, 230, 230);">
                        <table cellpadding="0" cellspacing="0" border="0">
                            <tbody>
                                <tr valign="top">
                                    <th style="padding-top: 19px;color:#0000bf;width:40px;"><img src="https://img.icons8.com/small/16/000000/checked-checkbox.png" /></th>
                                    <!-- 문의답변이 없을 경우 -->
                                    {% if iq.answer|length == 0 %}
                                    <td>문의가 접수되었습니다. 빠른 시일 내에 답변해드리겠습니다.</td>
                                    {% else %}
                                    <td>{{iq.answer}}</td>
                                    {% endif %}
                                </tr>

                            </tbody>
                        </table>
                    </div>
            </form>
            </div>
        </div>
        {% endfor %} {% if iq_list|length == 0 %}
        <!-- 1-2. 문의내역이 없을 경우 페이지버튼 여부. (없음) -->
        <div style="position:relative; padding-bottom:200px;">
            <div style="position:absolute;right:0;top:60px;">
                <button id="write" class="write"><span class="bhs_buttonsm yb" style="float:none;">글쓰기</span></button>
            </div>
        </div>
        <div class="layout-pagination">
            <div class="pagediv"></div>
        </div>
        {% endif %}
        <!-- end -->


        <!-- 페이지버튼 여부(있음. :after)-->
        {% if iq_list|length > 0 %}
        <div style="position:relative; padding-bottom:200px;">
            <div style="position:absolute;right:0;top:60px;">
                <button id="write" class="write"><span class="bhs_buttonsm yb" style="float:none;">글쓰기</span></button>
            </div>
        </div>
        <div class="layout-pagination">
            <div class="pagediv" style="font-size: 0px;padding-bottom:100px;">
                <!--페이지 번호 표시 부분 공백없도록 수정완료 -->
                <a href="/shop/mypage/mypage_qna.php?&amp;page=1" class="layout-pagination-button layout-pagination-first-page">맨 처음 페이지로 가기</a><a href="/shop/mypage/mypage_qna.php?&amp;page=1" class="layout-pagination-button layout-pagination-prev-page">이전 페이지로 가기</a>
                <strong class="layout-pagination-button layout-pagination-number __active">1</strong><a href="/shop/mypage/mypage_qna.php?&amp;page=1" class="layout-pagination-button layout-pagination-next-page">다음 페이지로 가기</a><a href="/shop/mypage/mypage_qna.php?&amp;page=1"
                    class="layout-pagination-button layout-pagination-last-page">맨 끝 페이지로 가기</a></div>
        </div>
        <!-- end -->
        {% endif %}
        <script>
            // $(".table_faq").click(function() {           problem 1. 기존에 있던 코드는 전체 행이 출력되는 문제가 발생했음.       
            //     var faq = $(".table_faq_plus");
            //     if (faq.css('display') === "none") {
            //         faq.css('display', 'block');
            //     } else if (faq.css('display') === "block") {
            //         faq.css('display', 'none');
            //     }
            // });

            // 1:1문의 목록에 있는 행을 누를 경우 이벤트 발생. - 클릭한 해당 문의 건에 대한 상세 문의내역을 표시함. 
            // problem 1-solve. 기존에 있던 문제를 해결하기 위해 index를 이용해 새로운 스크립트를 작성함.

            $(".table_faq").click(function() {
                var idx = $(".table_faq").index(this);
                $('.table_faq:eq(' + idx + ')').next().toggle();
            })


            // 글쓰기 페이지 이동 이벤트
            $(".write").click(function() {
                location.href = "{% url 'customer_service:iq_write' %}";

            })

            // 수정하기 페이지 이동 이벤트
            $("#edit").click(function() {
                document.getElementById("fm_send_tit").submit();
            })
        </script>




    </div>
</div>
{% endblock %}

customer_service(Django)/templates/customer_service/notice_page.html
{% extends 'base.html' %} {% block content %} {% load static%}

<head>
    <meta charset="utf-8">
    <script src="http://code.jquery.com/jquery.min.js"></script>
    <title>notice page</title>
    <link rel="stylesheet" href="{% static 'customer_service/css/customer.css' %}">
    <link rel="stylesheet" href="{% static 'customer_service/css/section2.css' %}">
    <link rel="stylesheet" href="{% static 'customer_service/css/normalize.css' %}">
    <script src="{% static 'customer_service/js/customer.js' %}"></script>

</head>



<div class="page_aticle aticle_type2">
    <div id="snb" class="snb_cc">
        <h2 class="tit_snb">고객센터</h2>
        <div class="inner_snb">
            <ul class="list_menu">
                <li class="on">
                    <a href="{% url 'customer_service:nt_list' %}">공지사항</a>
                </li>
                <li>
                    <a href="{% url 'customer_service:iq_list' %}">1:1 문의</a>
                </li>

            </ul>
        </div>
        <a href="{% url 'customer_service:iq_list' %}" class="link_inquire"><span class="emph">도움이 필요하신가요 ?</span> 1:1 문의하기</a>
    </div>

    <div class="page_aticle">

        <div class="page_section">
            <div class="head_aticle">
                <h2 class="tit">공지사항 <span class="tit_sub">컬리의 새로운 소식들과 유용한 정보들을 한곳에서 확인하세요.</span></h2>
            </div>

            <form name="frmList" action="shop/board/list.php?&" onsubmit="">
                <input type="hidden" name="id" value="notice">

            </form>
            <style>
                .notice .layout-pagination {
                    margin: 0
                }
                
                .eng2 {
                    color: #939393
                }
                
                .xans-board-listheader {
                    font-size: 12px
                }
            </style>
            <table width="100%" align="center" cellpadding="0" cellsapcing="0">
                <tbody>
                    <tr>
                        <td>
                            <div class="lists">
                                <table width="100%" class="list board" cellpadding="0" cellspacing="0">
                                    <thead>
                                        <tr class="list1">
                                            <th>분류</th>
                                            <th>제목</th>
                                            <th>작성자</th>
                                            <th>작성일</th>
                                            <th>조회</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- for -->
                                        {% for li in list %}
                                        <tr class="lists2">
                                            <td width="50" nowrap align="center">
                                                {{li.category}}</td>
                                            <td style="padding-left:10px; text-align:left; color:#999">
                                                <a href="{% url 'customer_service:nt_details' li.title %}">
                                                    <b>{{li.title}}</b>
                                                </a>
                                                <b></b></td>
                                            <td width="100" nowrap align="center">{{li.person_name}}</td>
                                            <td width="100" nowrap align="center" class="eng2">{{li.create_date|date:'Y-m-d'}}</td>
                                            <td width="30" nowrap align="center" class="eng2">{{li.hit}}</td>
                                        </tr>
                                        {% endfor %}
                                        <!-- end -->
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                </tbody>

            </table>
            <!-- 글쓰기는 관리자만 가능하도록 설정함 -->
            <!-- {% if user.username == 'admin' %} -->
            <div style="position:relative; padding-bottom:200px;">
                <div style="position:absolute;right:0;top:60px;">
                    <button id="write" class="write"><span class="bhs_buttonsm yb" style="float:none;">글쓰기</span></button>

                </div>
            </div>
            <!-- {% endif %} -->
            <div class="layout-pagination">
                <div class="pagediv" style="font-size:0px;">
                    <a class="layout-pagination-button layout-pagination-first-page" href="#">맨 처음 페이지로 가기</a>
                    <a href="#" class="layout-pagination-button layout-pagination-prev-page">이전 페이지로 가기</a>
                    <strong class="layout-pagination-button layout-pagination-number">1</strong>
                    <!-- 클릭시 __active 적용 (음영) -->
                    <a href="#" class="layout-pagination-button layout-pagination-number">2</a>
                    <a href="#" class="layout-pagination-button layout-pagination-number">3</a>
                    <a href="#" class="layout-pagination-button layout-pagination-number">4</a>
                    <a href="#" class="layout-pagination-button layout-pagination-number">5</a>
                    <a href="#" class="layout-pagination-button layout-pagination-next-page">다음 페이지로 가기</a>
                    <a href="#" class="layout-pagination-button layout-pagination-last-page">맨 끝 페이지로 가기</a>
                </div>
            </div>
            <table class="xans-board-search xans-board-search2">
                <tbody>
                    <tr>
                        <td class="input_txt">검색어 선택</td>
                        <td class="stxt">
                            <input type="checkbox" name="search[name]">이름
                            <input type="checkbox" name="search[subject]">제목
                            <input type="checkbox" name="search[contents]">내용&nbsp;
                        </td>
                        <td class="input_txt">&nbsp;</td>
                        <td>
                            <div class="search_bt">
                                <a href="#"><img src="https://img.icons8.com/fluent-systems-regular/24/000000/search--v2.png" align="absmiddle"></a>
                                <input type="text" name="search[word]" value="" required="">
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>

    <script>
        $(".write").click(function() {
            location.href = "{% url 'customer_service:nt_write' %}"
        })
    </script>

</div>
{%endblock%}

customer_service(Django)/templates/customer_service/notice_write.html
{% extends 'base.html' %} {% block content %} {% load static%}

<head>
    <meta charset="utf-8">
    <script src="http://code.jquery.com/jquery.min.js"></script>
    <title>customer service page_content</title>
    <link rel="stylesheet" href="{% static 'customer_service/css/customer.css' %}">
    <link rel="stylesheet" href="{% static 'customer_service/css/section2.css' %}">
    <link rel="stylesheet" href="{% static 'customer_service/css/normalize.css' %}">
    <script src="{% static 'customer_service/js/customer.js' %}"></script>


</head>
<div class="page_aticle aticle_type2">
    <div id="snb" class="snb_cc">
        <h2 class="tit_snb">고객센터</h2>
        <div class="inner_snb">
            <ul class="list_menu">
                <li class="on">
                    <a href="{% url 'customer_service:nt_list' %}">공지사항</a>
                </li>
                <li>
                    <a href="{% url 'customer_service:iq_list' %}">1:1 문의</a>
                </li>

            </ul>
        </div>
        <a href="{% url 'customer_service:iq_list' %}" class="link_inquire"><span class="emph">도움이 필요하신가요 ?</span> 1:1 문의하기</a>
    </div>
    <div class="page_section section_qna">
        <div class="head_aticle">
            <h2 class="tit">1:1 문의</h2>
        </div>

        <div class="part">
            <script>
                var element = document.getElementById('subject'); // 글쓰기 페이지에서는 적용되지 않는 스크립트.
                if (tit != null) element.value = tit;
                alert(element.value);
            </script>
            <form name="fm" id="fm" method="post" action="{% url 'customer_service:nt_write' %}" enctype="multipart/form-data" onsubmit="return chkForm(this)" style="height: 100%;">
                {% csrf_token %}
                <input type="hidden" name="mode" value="add_qna">
                <input type="hidden" name="itemcd" value="">
                <input type="hidden" name="sno" value="0">
                <table id="table_after" class="boardWrite2" width="100%">
                    <colgroup>
                        <col width="14%" align="right">
                    </colgroup>
                    <tbody>
                        <tr style="border-top:2px solid rgb(61, 0, 61)">
                            <th class="input_txt">제목</th>
                            <td><select name="itemcd" id="itemcd" required="" fld_esssential="" label="질문유형" class="select">
                        <option value="" >선택해주세요.</option>
                        <option value="공지">공지</option> 
                        <option value="감사인사">감사인사</option> 

                    </select><br>
                                <input type="text" id="subject" name="subject" style="width:60%;" value=" " required="" fld_esssential="" label="제목">
                            </td>
                        </tr>


                        <tr>
                            <th class="input_txt">내용</th>
                            <td class="edit_area" style="position: relative;">

                                <style>
                                    #qnaNotice .qna_goods {
                                        display: none
                                    }
                                </style>
                                <div id="qnaNotice">
                                    <div class="inner_qnaNotice">
                                        <div class="notice_qna">


                                        </div>
                                    </div>
                                </div>
                                <script>
                                    var qnaNotice = new Vue({
                                        el: '#qnaNotice',
                                        data: {
                                            getData: null,
                                            layerOn: true
                                        },
                                        methods: {
                                            update: function() {
                                                var $self = this;
                                                $.ajax({
                                                    type: 'GET',
                                                    url: campaginUrl + 'pc/notice/qna_info.html',
                                                    datatype: 'html',
                                                    async: true,
                                                }).done(function(result) {
                                                    $self.getData = result;
                                                });
                                            }
                                        }
                                    });
                                    $(document).ready(function() {
                                        qnaNotice.update();
                                    });
                                </script>
                                <!-- 내용 : contents = textarea 자리 -->
                                <textarea name="contents" id="contents" style="width:100%;height:474px; " class="editing_area " label="내용 "></textarea>
                            </td>
                        </tr>

                    </tbody>
                </table>

                <table width="100%">
                    <tbody>
                        <tr>
                            <td align="right" style="padding-top:5px; border:none;" id="avoidDbl">
                                <input type="submit" class="bhs_button yb" value="저장" style="float:none;">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>

        {% endblock %}